name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake bash bison bzip2 \
            cmake flex g++ intltool libtool-bin make sed \
            libtool libltdl-dev openssl libssl-dev \
            libxml-parser-perl patch perl \
            pkg-config scons unzip wget \
            xz-utils yasm

      - name: Build mingw-cross
        run: make

      - name: Compress mingw32 folder
        run: |
          tar -I lzma -cvf mingw32.tar.lzma mingw32

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MINGW32
          path: mingw32.tar.lzma
